name: Firebase Hosting CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write Firebase Service Account Key
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/firebase-key.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting --project community-agency-dev-d56c6
